language: php

php:
  - 5.5
  - 5.3

before_script:
  - php -r "eval('?>'.file_get_contents('https://getcomposer.org/installer'));"
  - php composer.phar update
  - sh build.sh

script:
  - phpunit -c Tests/app/phpunit.xml
